### ISSUE TITLE
bug: Problema navegación +tag-list

### ISSUE THREAD

**Issue by DisoQ** [DachTeam/.github#1]
Al usar el comando **+tag-list** y usar su navegación con botones (Respectivamente << y >>) no se muestra la 2da página, con ello pasamos de la pagina 1 a la 3 y viceversa.

**Pasos a seguir**
1. Ve a un canal de comandos para el uso de @DACH
2. Usa el comando +tag-list / +list / +lista.
3. Navega con los botones y mira el error mencionado anteriormente.

**Resultado esperado**
No se mostrará la segunda página pero si el resto.

**Capturas**
[Video de demostración](https://cdn.discordapp.com/attachments/649347003016413195/944264046474039336/screen-20220218-110728.mp4) 

**Contexto adicional**
Dato extra, al usar +top y avanzar a la segunda página se cambiaba el titulo de Top usuarios Discord Ayuda a Tags Discord Ayuda, luego de arreglarlo ocurre este error.

**Comment by chikof** [comment]
Lo he arreglado, parece que estaba intentando enviar un embed con una descripción de más de `1024` caracteres. El error era que una etiqueta tenía una descripción **MUY** larga.
